### ISSUE TITLE
QFontDatabase constructor and destructor unavailable

### ISSUE THREAD

**Issue by Libaud** [davidbannon/libqt6pas#11]
QFontDatabase constructor and destructor unavailable in qfontdatabase_c.h :
C_EXPORT QFontDatabaseH QFontDatabase_Create();
C_EXPORT void QFontDatabase_Destroy(QFontDatabaseH handle);
This do not permit to build Typhon 8.x on Linux (Mint 21.x with QT 6 for example).

**Comment by davidbannon** [comment]
Hmm, thats interesting, if Z has updated the interface, my scripts would have alerted me. I will have a look as soon as I can. Thanks for the heads up !

Davo

**Comment by davidbannon** [comment]
Libaud, I see no recent changes to qfontdatabase, there have been some small changes to the interface, ones that should possibly require an updated version number so I have logged an issue to clarify.

Are you using Lazarus Main here ?   I do not base these libraries on Typhon, if they make changes to the code they ship, then I am afraid you need to use their libraries. If Typhon have not changed the code, then we would both be better off you using Lazarus Main, no point in me reporting bugs in Typhon to Lazarus !

If I get some time free, I'll run some tests of mine own against Lazarus.

Davo

**Comment by davidbannon** [comment]
OK, no answer from Libaud, I guess he was using CT.
Close
